// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EducationItem = { school: string, degree: string | null, field: string | null, start: string | null, end: string | null, honors: Array<string>, };
