// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExperienceItem = { company: string, role: string, 
/**
 * Free-form date string ("2023.01", "Jan 2023", "2023 年 1 月"). The model
 * preserves whatever the user typed; structured parsing is a renderer or
 * later-phase concern.
 */
start: string | null, 
/**
 * `None` or "Present" both mean "still in role"; renderers decide display.
 */
end: string | null, location: string | null, bullets: Array<string>, };
