// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Open key/value field — LinkedIn, Website, Nationality, Visa, etc.
 * `key` is a stable machine identifier; `label` is the display name (can be
 * localized by the caller); `value` is the actual content.
 */
export type ExtraField = { key: string, label: string, value: string, };
