// Frontend-only settings type for the Customize page.
// Not generated by ts-rs — lives entirely in the frontend until
// the Rust backend gains matching fields in ResumeMeta.

export type ResumeSettings = {
  /** Display language for the resume, e.g. "en-US", "zh-CN". */
  language: string;
  /** Date format string, e.g. "MM/DD/YYYY", "DD/MM/YYYY". */
  dateFormat: string;
  /** Page size, e.g. "us-letter", "a4". */
  pageFormat: string;
};

export const DEFAULT_SETTINGS: ResumeSettings = {
  language: "en-US",
  dateFormat: "MM/DD/YYYY",
  pageFormat: "us-letter",
};
