// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight tag enum for menus, filters, ordering — anywhere code needs to
 * talk about *which kind of section* without carrying the payload.
 */
export type SectionKind = "summary" | "experience" | "education" | "skills";
