// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EducationSection } from "./EducationSection";
import type { ExperienceSection } from "./ExperienceSection";
import type { SkillsSection } from "./SkillsSection";
import type { SummarySection } from "./SummarySection";

/**
 * Closed enum of all section kinds.
 *
 * JSON shape: `{ "type": "experience", ...payload }` — the `type` discriminator
 * is stable across versions and the rest of the object is the variant payload
 * flattened in. Adding a new variant is a deliberate breaking decision that
 * the compiler flags in every renderer's `match`.
 */
export type Section = { "type": "summary" } & SummarySection | { "type": "experience" } & ExperienceSection | { "type": "education" } & EducationSection | { "type": "skills" } & SkillsSection;
