// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillGroup } from "./SkillGroup";

export type SkillsSection = { groups: Array<SkillGroup>, };
